version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    ports:
      - 15433:5432
  rubygems:
    build:
      context: bulid_dockerfiles
      dockerfile: Dockerfile-rubygems
    volumes:
      - "$PWD:/scripts"
      - rubygems_vol:/vender/bundle
volumes:
  postgres_vol:
  rubygems_vol:
