version: '3'
services:
  redis:
    image: redis
    ports:
      - 16379:6379
  db:
    image: postgres
    volumes:
      - app_database_vol:/var/lib/postgresql/data
    ports:
      - 15432:5432
volumes:
  app_database_vol:
